version: '3.8'
services: 
    app:
        image: node:10
        command: sh -c "npm install && npm run build && npm run start:prod"
        ports: 
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app